server:
  port: 8082

spring:
  application:
    name: trainee-search-service
  elasticsearch:
    rest:
      uris: localhost:9200
      username: elastic
      password:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/trainee
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        namespace: 1ac8447d-28f3-4f59-b428-271e95740ddf
        server-addr: localhost:8848
        group: TRAINEE

mybatis:
  mapper-locations: classpath:com/yuxing/trainee/search/infrastructure/dao/xml/*.xml

trainee-search:
  log:
    level: DEBUG
  index:
    goods: goods
