server:
  port: 8082

spring:
  application:
    name: trainee-search-service
  elasticsearch:
    rest:
      uris: localhost:9200
      username: elastic
      password:
  cloud:
    nacos:
      discovery:
        namespace: 1ac8447d-28f3-4f59-b428-271e95740ddf
        server-addr: localhost:8848
        group: TRAINEE

trainee-search:
  log:
    level: DEBUG
  index:
    goods: goods
